version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.51
    container_name: otel-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "14250:14250"
    networks:
      - otel-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./configs/otel-collector-config.yml:/etc/otel-collector-config.yml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
    networks:
      - otel-network

  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: otel-prometheus
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - otel-network

  grafana:
    image: grafana/grafana:10.2.3
    container_name: otel-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=otel123
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./configs/grafana-provisioning:/etc/grafana/provisioning:ro
      - ./dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3001:3000"
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge